version: '3'

services:  
    pgsql:
        image: 'postgres:14'
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: '${POSTGRES_DB}'
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_SCHEMA: 'public'
        volumes:
            - 'my-pgsql:/var/lib/postgresql/data'
        networks:
            - my-network
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'my-redis:/data'
        networks:
            - my-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
  my-network:
    external: true
volumes:
    my-pgsql:
        driver: local
    my-redis:
        driver: local
    